{% set name = "transforms3d" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8b5df30eaedbee556e81c6938e55aab5365894e47d0a17615d7db7fd2393680

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - versioneer
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.15

test:
  requires:
    - pytest
    - nose
    - scipy
    - sympy
  source_files:
    - transforms3d/tests
  imports:
    - transforms3d
    - transforms3d.derivations
    - transforms3d.tests
  commands:
    - py.test --pyargs transforms3d

about:
  home: https://github.com/matthew-brett/transforms3d
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Functions for 3D coordinate transformations
  doc_url: http://matthew-brett.github.io/transforms3d/
  dev_url: https://github.com/matthew-brett/transforms3d

extra:
  recipe-maintainers:
    - tschoonj
