{% set name = "transforms3d" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73e0a4dbc7eceacfb5314665da7b388398cfbea39d92257a751abf4429a442bb

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy

test:
  requires:
    - pytest ==3.10.1
    - nose
  source_files:
    - transforms3d/tests
  imports:
    - transforms3d
    - transforms3d.derivations
    - transforms3d.tests
  commands:
    - py.test --pyargs transforms3d

about:
  home: https://github.com/matthew-brett/transforms3d
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Functions for 3D coordinate transformations
  doc_url: http://matthew-brett.github.io/transforms3d/
  dev_url: https://github.com/matthew-brett/transforms3d

extra:
  recipe-maintainers:
    - tschoonj
