travis:
  secure:
    BINSTAR_TOKEN: WdRVmWM9QWhwV+yZ+OusWKsMrfnzPVR4v3Owj33YZoEWmPUrq+HqiRSRQruN7iodO+/TVsrom2nBFohOlvl/BelF5qdq4Bz6DMXetol4mhvv5aBPpsiMScpfrk67f2uh+x1w/50EIMTsmIIafB5x3xEF+mCjmdtKGMjqlcEE8ZKSHHhU4gjNr11OCkZSHqkAOf6SIAp7lRGa3pUz2qHWSlEjvDzijpO1YYoCzLeAucj2ow75Ud2pVIlH+0rAIa2IQNjzWOGKLIgaUiLwCxDxkOztFcj0y+cVQYHTmzaiOl5NTPLtd1ivaEwcYla3FMoNPeqt/uY9u59UjNXaPDt/u3wrB86I8nmLZTHTFyEvwBGK2M+jAonG+ZhsHENMnajzzWpuusdwmwMKuRIlaynmS0NAofepJWlI9XS3cdLzdMgAFjLvNued7IwueQoSPHbgENlspHQOj58RHRYExlCYNrEhtDyVve2wgSRb2CXeG9EuKEE2/VHW94c5WVi9oLm+AqAVOUooRl7TPWCt/DafQSX0sHcxWXwwPFv1LCTrd1+rA58lnvIC1/sfZKmjo8tQk7I1xIk0H8nEcl+GXJQnEFCxTP1Ss07bjnAv47cJool6bcJP29Op1jh7xqdIHvedCNe3Z2dbb6GYvOt4SjIiUpWu3iMDomHlFijomtC1c8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
